"""add tags and tag questions

Revision ID: 8c7f24f69511
Revises: 2909a6cad7ea
Create Date: 2026-05-05 14:22:03.956415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c7f24f69511'
down_revision: Union[str, Sequence[str], None] = '2909a6cad7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
